# This is a rather superficial check that only verifies compliance with the formatting style.

name: Java code format checks

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Check code formatting compliance
        run: mvn spotless:check